name: Lint, test and deploy in three jobs
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Run lint
            run: echo "npm run lint"
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
          - name: Run test
            run: echo "npm run test"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Run build
            run: echo "npm run build"